services:
  serving:
    build: ./serving
    ports:
      - "8080:8080"
    volumes:
      - ./webroot:/webroot
  
  renewer:
    build: ./renewer
    env_file:
      - ./renewer/.env
    volumes:
      - ./acme:/acme.sh
      - ./webroot:/webroot
      - ./logs:/logs
